export const RESOURCE_DATA
  = [
    // { name: "最新", id: "最新" }""
    //{ id: '111', url: 'http://19.16.240.45:6080/arcgis/rest/services/GHSJ_UPDATE/JSYDGZQ20180622/MapServer', serviceType: 'image', title: '国土用途规划分类', name: '国土用途规划分类', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '111', url: 'http://19.15.73.111/arcgisserver12/rest/services/土地规划类数据服务/广东省土地利用规划/MapServer', serviceType: 'wmts', useProxy: false, title: '广东省土地利用规划', name: '广东省土地利用规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '22', url: 'http://19.15.73.111/arcgisserver12/rest/services/三线管控/广东省城镇开发边界/MapServer', serviceType: 'wmts', useProxy: false, title: '广东省城镇开发边界', name: '广东省城镇开发边界', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '33', url: 'http://19.15.73.111/arcgisserver12/rest/services/三线管控/生态保护红线/MapServer', serviceType: 'wmts', useProxy: false, title: '生态保护红线', name: '生态保护红线', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    // { id: '44', url: 'http://19.18.128.73:6080/arcgis/rest/services/2000服务/永久基本农田2000/MapServer', serviceType: 'image', title: '永久基本农田', name: '永久基本农田', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '44', url: 'http://19.15.73.111/arcgisserver12/rest/services/农田类数据服务/广东省永久基本农田_2017/MapServer', serviceType: 'wmts', useProxy: false, title: '永久基本农田', name: '永久基本农田', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '50', url: 'http://19.15.73.111/arcgisserver12/rest/services/试评价结果/生态保护等级评价结果/MapServer', serviceType: 'image', title: '生态保护等级', name: '生态保护等级', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    // { id: '51', url: 'http://19.15.73.111/arcgisserver12/rest/services/试评价结果/生态保护等级评价结果/MapServer', serviceType: 'image', title: '生态保护重要性', name: '生态保护重要性', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '52', url: 'http://19.15.73.111/arcgisserver12/rest/services/试评价结果/农业承载力评价结果/MapServer', serviceType: 'image', title: '农业承载等级', name: '农业承载等级', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '53', url: 'http://19.15.73.111/arcgisserver12/rest/services/试评价结果/农业适宜性评价结果/MapServer', serviceType: 'image', title: '农业生产适宜性', name: '农业生产适宜性', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '54', url: 'http://19.15.73.111/arcgisserver12/rest/services/试评价结果/城镇承载力评价结果/MapServer', serviceType: 'image', title: '城镇承载等级', name: '城镇承载等级', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '55', url: 'http://19.15.73.111/arcgisserver12/rest/services/试评价结果/城镇适宜性评价结果/MapServer', serviceType: 'image', title: '城镇开发适宜性', name: '城镇开发适宜性', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '56', url: 'http://19.16.240.45:6080/arcgis/rest/services/GHSJ_UPDATE/QMDLTB20180622/MapServer', serviceType: 'image', title: '土地规划期末地类图斑', name: '土地规划期末地类图斑', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '57', url: 'http://19.16.240.45:6080/arcgis/rest/services/GHSJ_UPDATE/TDYT20180622/MapServer', serviceType: 'image', title: '土地规划用途分区', name: '土地规划用途分区', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    //{ id: '58', url: 'http://19.18.128.73:6080/arcgis/rest/services/2000服务/城市总体规划2000/MapServer', serviceType: 'image', title: '城市总体规划', name: '城市总体规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '58', url: 'http://19.15.73.111/arcgisserver12/rest/services/城市规划类数据服务/广东省城市总体规划/MapServer', serviceType: 'wmts', useProxy: false, title: '城市总体规划', name: '城市总体规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '59', url: 'http://19.15.73.111/arcgisserver12/rest/services/一张图展示界面/主体功能区/MapServer', serviceType: 'image', title: '主体功能区', name: '主体功能区', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '65', url: 'http://19.15.73.111/arcgisserver12/rest/services/广东省海洋规划/海洋综合整治规划/MapServer', serviceType: 'image', title: '海洋功能区划', name: '海洋功能区划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '655', url: 'http://19.15.73.111/arcgisserver12/rest/services/一张图展示界面/自然保护区/MapServer', serviceType: 'image', title: '自然保护区', name: '自然保护区', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '01', url: 'http://19.15.73.117:6080/arcgis/rest/services/省级空间规划成果/广东省魅力空间体系图/MapServer', serviceType: 'image', title: '风景名胜区', name: '风景名胜区', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '02', url: 'http://19.15.73.111/arcgisserver12/rest/services/一张图展示界面/地质公园/MapServer', serviceType: 'image', title: '地质公园', name: '地质公园', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '03', url: 'http://19.15.73.111/arcgisserver12/rest/services/一张图展示界面/地质灾害防治规划/MapServer', serviceType: 'image', title: '地质灾害防治规划', name: '地质灾害防治规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '04', url: 'http://19.15.73.111/arcgisserver12/rest/services/广东城镇体系规划/综合交通设施规划/MapServer', serviceType: 'image', title: '高速公路网规划', name: '高速公路网规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '05', url: 'http://19.15.73.117:6080/arcgis/rest/services/广东省海域权属现状数据/MapServer', serviceType: 'image', title: '港口规划', name: '港口规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '06', url: 'http://19.15.73.117:6080/arcgis/rest/services/广东省近海海域/MapServer', serviceType: 'image', title: '航道规划', name: '航道规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    //{ id: '07', url: 'http://19.18.128.73:6080/arcgis/rest/services/2000服务/三调一上DLTB/MapServer', serviceType: 'image', title: '三调地类图斑', name: '三调地类图斑', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '07', url: 'http://19.16.240.45:6080/arcgis/rest/services/ZTSJ/DLTB2018/MapServer', serviceType: 'image', title: '三调地类图斑', name: '三调地类图斑', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '08', url: 'http://19.16.240.25:6080/arcgis/rest/services/ServerTD/TDXZ2016/MapServer', serviceType: 'image', title: '现状图', name: '现状图', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '09', url: 'http://19.18.128.73:6080/arcgis/rest/services/TDGH/全省县级中心城区范围/MapServer', serviceType: 'image', title: '县级中心城区范围线', name: '县级中心城区范围线', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '0909', url: 'http://19.18.128.73:6080/arcgis/rest/services/TDGH/GDZXCQFW/MapServer', serviceType: 'image', title: '市级中心城区范围线', name: '市级中心城区范围线', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '10', url: 'http://19.18.128.73:6080/arcgis/rest/services/TDGH/GDKFQ/MapServer', serviceType: 'image', title: '开发区范围', name: '开发区范围', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    // { id: '11', url: 'http://19.18.128.73:6080/arcgis/rest/services/TDGH/GDKFQ/MapServer', serviceType: 'image', title: '产业园范围', name: '产业园范围', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '12', url: 'http://19.15.73.117:6080/arcgis/rest/services/用地红线/MapServer', serviceType: 'image', title: '用地红线', name: '用地红线', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '13', url: 'http://19.18.128.73:6080/arcgis/rest/services/TDGH/YSHX/MapServer', serviceType: 'image', title: '预审红线', name: '预审红线', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '14', url: 'http://19.15.73.111/arcgisserver12/rest/services/城镇内部用地/广东省县区人口/MapServer', serviceType: 'image', title: '广东省县区人口', name: '广东省县区人口', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    //{ id: '112', url: 'http://172.16.8.112:8081/geostar/GD_SLGYM/wmts', serviceType: 'wmts', useProxy: false, title: '森林公园',layer:'LYJ_SLGYM', style:'LYJ_SLGYM', matrixid:'Matrix_LYJ_SLGYM_0', name: '森林公园', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '113', url: 'http://19.15.73.111/yztfw/geostar/GD_SLGYD/wmts', serviceType: 'wmts', useProxy: false, title: '森林公园点',layer:'LYJ_SLGYD', style:'LYJ_SLGYD', matrixid:'Matrix_LYJ_SLGYD_0', name: '森林公园点', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '114', url: 'http://19.15.73.111/yztfw/geostar/GD_HLFB/wmts', serviceType: 'wmts', useProxy: false, title: '河流分布',layer:'SLT_HLFB', style:'SLT_HLFB', matrixid:'Matrix_SLT_HLFB_0', name: '河流分布', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '115', url: 'http://19.15.73.111/yztfw/geostar/GD_TLGH/wmts', serviceType: 'wmts', useProxy: false, title: '铁路规划',layer:'JTYST_TLGH', style:'JTYST_TLGH', matrixid:'Matrix_JTYST_TLGH_0', name: '铁路规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '116', url: 'http://19.15.73.111/yztfw/geostar/GD_CJGDGH/wmts', serviceType: 'wmts', useProxy: false, title: '城际轨道',layer:'JTYST_CJGDGH', style:'JTYST_CJGDGH', matrixid:'Matrix_JTYST_CJGDGH_0', name: '城际轨道', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
    { id: '117', url: 'http://19.15.73.111/yztfw/geostar/GD_2016JCGH/wmts', serviceType: 'wmts', useProxy: false, title: '机场规划',layer:'JTYST_2016JCGH', style:'JTYST_2016JCGH', matrixid:'Matrix_JTYST_2016JCGH_0', name: '机场规划', isLeaf: true, serviceStatus: '1', collectStatus: '1' },
  ]

export const ZHUANTI_DATA = [
  { id: '56', name: '国土空间规划底图' },
  { id: '57', name: '400' },
  { id: '58', name: '农田' },
  { id: '59', name: '农田补充文字' },
  { id: '65', name: '生态保护红线划定' },
  { id: '655', name: '生态红线' },
  { id: '01', name: '生态红线-400' },
  { id: '02', name: '生态红线-600' },
  { id: '03', name: '生态红线补偿文字' },
  { id: '04', name: '永久基本农田划定成果' }]
